### ISSUE TITLE
Images in a blog post

### ISSUE THREAD

**Issue by rafa1944** [spatie/freek.dev#106]
Hi Freek & guys!

I can´t find a way to upload an image to a blog post from Nova admin panel as I can see on any post:

![CleanShot 2020-12-21 at 19 14 55](https://user-images.githubusercontent.com/3229521/102808629-e1711b00-43c0-11eb-9ee7-e4cd00451fed.jpg)

Any help? Is there anything I´m missing?

Thanks guys

**Comment by freekmurze** [comment]
I never got to implementing this in a nice way, so I manually upload files to server, there isn't anything in Nova to do this yet.
