### ISSUE TITLE
Better post excerpts

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/freek.dev#57]
Ideally, the excerpt is manually set by a `<!--more-->` tag. Maybe do this for new posts and keep automatically generated exceprts for old content?

Automatically generated excerpts could be smarter too.

- Don't cut off half paragraphs, so `…` is never needed
- Sometimes subtitles are part of the excerpt, so you end up with excerpts like `...foo bar. # Title in between bla bla bla...`

**Comment by freekmurze** [comment]
> Ideally, the excerpt is manually set by a  tag

Done!

> Automatically generated excerpts could be smarter too.

Going to leave it like it is for now. If I see a wrong excerpt somewhere, I'll just update the post to make use of `<!--more-->`
