### ISSUE TITLE
Lazy load third party content

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/freek.dev#59]
- Embedded tweets
- Embedded videos
- Disqus

Might look into a generic lazy load solution with `IntersectionObserver`.

**Comment by sebastiandedeyne** [comment]
This needs to be applied to all post content, not sure what the best place is?

https://github.com/spatie/freek.dev/blob/2e97d8b97eebd1d82d7de3eb70c33400ad6508ce/resources/views/front/posts/partials/list.blade.php#L14

**Comment by freekmurze** [comment]
Refactored it a bit
