### ISSUE TITLE
Set webfonts to production mode

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/freek.dev#63]
We need to upload the font bundle to the server before going into production. Since the fonts aren't open source, we can't keep them in the repo either. To discuss.

**Comment by freekmurze** [comment]
We could put those fonts in a private repo and have that repo available on the server.

Main app is here`/home/forge/freek.dev/current`. Fonts could be here `/home/forge/freek.dev-fonts`

**Comment by sebastiandedeyne** [comment]
Would be good enough to just gitignore them tbh, they don't change much. We could save them in `storage` since that's persisted across deploys.

**Comment by freekmurze** [comment]
Sounds good to me!

**Comment by freekmurze** [comment]
Add this to deploy script

```
ln -nfs {{ $baseDir }}/persistent/fonts {{ $newReleaseDir }}/public/fonts;
```
