### ISSUE TITLE
Search results still have some hard coded data

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/freek.dev#64]
https://github.com/spatie/freek.dev/blob/9974ac5ed667b92be786178c9699c1ac3f08c739/resources/js/search/Search.js#L40

Waiting on a search index update.

**Comment by freekmurze** [comment]
Import done 
![image](https://user-images.githubusercontent.com/483853/58805779-0c482280-8615-11e9-8909-91d8c48e694c.png)
