### ISSUE TITLE
webmentions & signature error

### ISSUE THREAD

**Issue by abr4xas** [spatie/freek.dev#79]
Hey Freek, I was trying to implement the "[How to add webmentions to a Laravel powered blog](https://freek.dev/1406-how-to-add-webmentions-to-a-laravel-powered-blog)" but I'm having some issues with the signature validation. 

My error is: 

```
Spatie\WebhookClient\Exceptions\WebhookFailed
The signature is invalid.
```

My callback secret is the same value from `webmentions.webhook_secret` entry in the 
`config/services.php`

I'm using this code but IDK what's happening

https://github.com/spatie/freek.dev/blob/5afed5e5e29712a6fc602487ea8e035c6b82560a/app/Services/Webmentions/WebmentionWebhookSignatureValidator.php#L10

**Comment by freekmurze** [comment]
Hi,

I currenlty don't have the time to look at individual projects. If you feel the webhook client package, open an issue at the repo.
