### ISSUE TITLE
As I use ImportWp (Help)

### ISSUE THREAD

**Issue by lucenarenato** [spatie/freek.dev#87]
## As I use ImportWp ("php artisan import: wp"), I ran but the error. 
```
Illuminate \ Database \ QueryException: SQLSTATE [42S02]: Base table or view not found: 1146 Table 'murze.wp_posts' doesn't exist (SQL: select * from `wp_posts` where` post_status` = publish and `post_type` = = post)
```
, do you have to place the Wordpress tables in the same table as the project? Help!

- Sincerely: Renato Lucena - cpdrenato@gmail.com

**Comment by freekmurze** [comment]
That table is already deleted. I'll delete that command soon too.
